classdef AmplifierRespControlView < handle
    %AMPLIFIERRESPCONTROLVIEW Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Access = private)
        controller
        channelRadioBtns
        channelSelectBoxes
        shiftY
        scaleY
        shiftYText
        scaleYText
        thresholdTxt
        directionTxt
    end
    
    methods
        
        function obj = AmplifierRespControlView(model, controller, layout)
            obj.controller = controller;
            channels = controller.getChannels;
            
            obj.channelRadioBtns = struct();
            obj.channelSelectBoxes = struct();
            
            controlPannel = uiextras.Panel(...
                'Parent', layout,...
                'Title', 'Controls',...
                'Padding', 5 );
            controlLayout = uiextras.HBoxFlex(...
                'Parent',controlPannel,...
                'Padding', 5, 'Spacing', 5);
            
            amplifierLayout  = uiextras.VBox(....
                'Parent', controlLayout);
            
            for i = 1:length(channels)
                obj.channelSelectBoxes.(channels{i}) = uicontrol(...,
                    'Parent', amplifierLayout,...
                    'Style','checkbox',...
                    'String',sprintf('Channel %d',i),...
                    'Value',0,...
                    'callback', @(h, d)updatePlots(obj.controller,h ,d, obj.channelSelectBoxes, model),...
                    'Tag',channels{i});
            end
            
            spikeDetecttionLabel  = uiextras.VBox(....
                'Parent', controlLayout);
            uicontrol(...,
                'Parent', spikeDetecttionLabel,...
                'Style','text',...
                'String','Spike Detection');
            uicontrol(...,
                'Parent', spikeDetecttionLabel,...
                'Style','text',...
                'String','Threshold');
             uicontrol(...,
                 'Parent', spikeDetecttionLabel,...
                 'Style','pushbutton',...
                 'String','Start', ...
                 'callback', @(h, d)enableSpikeDetection(obj.controller, h, d, obj.channelRadioBtns, obj.thresholdTxt, model));
            
             spikeDetecttionLayout  = uiextras.VBox(....
                 'Parent', controlLayout);
             uiextras.Empty('Parent', spikeDetecttionLayout)
             obj.thresholdTxt = uicontrol(...,
                 'Parent', spikeDetecttionLayout,...
                 'Style','Edit',...
                 'String','00.000',...
                 'callback', @(h, d)setThreshold(obj.controller, h, d, obj.channelRadioBtns, model));

             uicontrol(...,
                 'Parent', spikeDetecttionLayout,...
                 'Style','pushbutton',...
                 'String','Stop');

            scalingLabelLayout  = uiextras.VBox(....    
                'Parent', controlLayout);
            obj.channelRadioBtns.('default')= uicontrol(...
                'Parent', scalingLabelLayout,...
                'Style','radiobutton',...
                'String', 'Auto Scale',...
                'callback', @(h, d)autoScale(obj.controller, h, d, obj.shiftY, obj.scaleY, obj.channelRadioBtns, model),...
                'Tag', 'default',...
                'Value',0);
            
            for i = 1:length(channels)
                obj.channelRadioBtns.(channels{i}) = uicontrol(...
                    'Parent', scalingLabelLayout,...
                    'Style','radiobutton',...
                    'String',sprintf('Scale Channel %d',i),...
                    'callback', @(h, d)selectScalingChannel(obj.controller,h ,d, obj.shiftY, obj.scaleY, obj.channelRadioBtns, model),...
                    'Tag',channels{i},...
                    'Value',i == 1);
            end
            
            scalingLayout  = uiextras.VBox(....
                'Parent', controlLayout);
            obj.shiftYText = uicontrol(...,
                'Parent', scalingLayout,...
                'Style', 'text',...
                'String', 'Vertical Shift');
            obj.shiftY = uicontrol(...
                'Parent', scalingLayout,...
                'Style','slider',...
                'Min', 0, 'Max', 10000, 'Value', 0,...
                'SliderStep', [0.05 0.2],...
                'callback', @(h, d)shiftYAxis(obj.controller, h, d, obj.channelRadioBtns, model),...
                'Tag', channels{i});
            obj.scaleYText = uicontrol(...
                'Parent', scalingLayout,'Style','text',...
                'String', 'Vertical Scale');
            obj.scaleY = uicontrol(...
                'Parent', scalingLayout,'Style','slider',...
                'Min', 1, 'Max', 10, 'Value', 1,...
                'SliderStep', [0.05 0.2],...
                'callback', @(h, d)scaleYAxis(obj.controller, h, d, obj.channelRadioBtns, model),...
                'Tag', channels{i});
            
            set(controlLayout, 'Sizes', [100 100 80 120 300]);
        end
    end
end

