classdef AmplifierRespControlView < handle
    %AMPLIFIERRESPCONTROLVIEW Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Access = private)
        controller
        channelRadioBtns
        channelSelectBoxes
        sliderX
        sliderY
        sliderXText;
        sliderYText;
    end
    
    methods
        
        function obj = AmplifierRespControlView(model, controller, layout)
            obj.controller = controller;
            channels = controller.getChannels;
            
            obj.channelRadioBtns = struct();
            obj.channelSelectBoxes = struct();
            
            controlPannel = uiextras.Panel(...
                'Parent', layout,...
                'Title', 'Controls',...
                'Padding', 5 );
            controlLayout = uiextras.HBoxFlex(...
                'Parent',controlPannel,...
                'Padding', 5, 'Spacing', 5);
            
            amplifierLayout  = uiextras.VBox(....
                'Parent', controlLayout);
            
            for i = 1:length(channels)
                obj.channelSelectBoxes.(channels{i}) = uicontrol(...,
                    'Parent', amplifierLayout,...
                    'Style','checkbox',...
                    'String',sprintf('Channel %d',i),...
                    'Value',0,...
                    'callback', @(h, d)updatePlots(obj.controller,h ,d, obj.channelSelectBoxes, model),...
                    'Tag',channels{i});
            end
            
            
            scalingLabelLayout  = uiextras.VBox(....
                'Parent', controlLayout);
            obj.channelRadioBtns.('default')= uicontrol(...
                'Parent', scalingLabelLayout,...
                'Style','radiobutton',...
                'String', 'Auto Scale',...
                'callback', @(h, d)autoScale(obj.controller, h, d, obj.sliderX, obj.sliderY, obj.channelRadioBtns, model),...
                'Tag', 'default',...
                'Value',1);
            
            for i = 1:length(channels)
                obj.channelRadioBtns.(channels{i}) = uicontrol(...
                    'Parent', scalingLabelLayout,...
                    'Style','radiobutton',...
                    'String',sprintf('Scale Channel %d',i),...
                    'callback', @(h, d)selectScalingChannel(obj.controller,h ,d, obj.sliderX, obj.sliderY, obj.channelRadioBtns, model),...
                    'Tag',channels{i},...
                    'Value',0);
            end
            
            scalingLayout  = uiextras.VBox(....
                'Parent', controlLayout);
            obj.sliderXText = uicontrol(...,
                'Parent', scalingLayout,...
                'Style','text',...
                'String','Horizontal Scale X min = 0.0 & X max = 1.0 ');
            obj.sliderX = uicontrol(...
                'Parent', scalingLayout,...
                'Style','slider',...
                'Min',0,'Max',100,'Value',25,...
                'SliderStep',[0.05 0.2],...
                'String','Horizontal Scale Y min = 0.0 & Y max = 1.0', ...
                'callback', @(h, d)handleSliderX(obj.controller,h ,d ),...
                'Tag',channels{i});
            obj.sliderYText = uicontrol(...
                'Parent', scalingLayout,'Style','text',...
                'String','Vertical Scale');
            obj.sliderY = uicontrol(...
                'Parent', scalingLayout,'Style','slider',...
                'Min',0,'Max',100,'Value',25,...
                'SliderStep',[0.05 0.2],...
                'String','Vertical Scale',...
                'callback', @(h, d)handleSliderY(obj.controller,h ,d ),...
                'Tag',channels{i});
            
            set(controlLayout, 'Sizes', [-1 -6 -1]);
        end
    end
end

